// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotFinder.AuthService.Data.Context;

#nullable disable

namespace SpotFinder.AuthService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auth")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotFinder.AuthService.Data.Entities.User", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()").HasColumnType("uuid");
                b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("email");
                b.Property<string>("PasswordHash").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("password_hash");
                b.Property<string>("FullName").HasMaxLength(150).HasColumnType("character varying(150)").HasColumnName("full_name");
                b.Property<string>("PhoneNumber").HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("phone_number");
                b.Property<string>("AvatarUrl").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("avatar_url");
                b.Property<string>("Provider").IsRequired().HasMaxLength(50).HasDefaultValue("local").HasColumnType("character varying(50)").HasColumnName("provider");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasDefaultValue("user").HasColumnType("character varying(50)").HasColumnName("role");
                b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("boolean").HasColumnName("is_active");
                b.Property<DateTime>("CreatedAt").HasDefaultValueSql("now()").HasColumnType("timestamptz").HasColumnName("created_at");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamptz").HasColumnName("updated_at");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("users", "auth");
            });

            modelBuilder.Entity("SpotFinder.AuthService.Data.Entities.UserRefreshToken", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()").HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<string>("Token").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("token");
                b.Property<DateTime>("ExpiresAt").HasColumnType("timestamptz").HasColumnName("expires_at");
                b.Property<bool>("IsRevoked").HasDefaultValue(false).HasColumnType("boolean").HasColumnName("is_revoked");
                b.Property<DateTime>("CreatedAt").HasDefaultValueSql("now()").HasColumnType("timestamptz").HasColumnName("created_at");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("user_refresh_tokens", "auth");
            });

            modelBuilder.Entity("SpotFinder.AuthService.Data.Entities.UserFavorite", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<Guid>("VenueId").HasColumnType("uuid").HasColumnName("venue_id");
                b.Property<DateTime>("CreatedAt").HasDefaultValueSql("now()").HasColumnType("timestamptz").HasColumnName("created_at");
                b.HasKey("UserId", "VenueId");
                b.ToTable("user_favorites", "auth");
            });

            modelBuilder.Entity("SpotFinder.AuthService.Data.Entities.UserVisit", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasDefaultValueSql("gen_random_uuid()").HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<Guid>("VenueId").HasColumnType("uuid").HasColumnName("venue_id");
                b.Property<DateTime>("VisitedAt").HasDefaultValueSql("now()").HasColumnType("timestamptz").HasColumnName("visited_at");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("user_visits", "auth");
            });
#pragma warning restore 612, 618
        }
    }
}
