// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotFinder.VenueService.Data.Context;

#nullable disable

namespace SpotFinder.VenueService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315231726_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.ConceptTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("concept_tags", "venue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Birthday",
                            NameTr = "Doğum Günü"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Romantic",
                            NameTr = "Romantik"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Scenic View",
                            NameTr = "Manzaralı"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Outdoor",
                            NameTr = "Açık Hava"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Breakfast",
                            NameTr = "Kahvaltı"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Live Music",
                            NameTr = "Canlı Müzik"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Family Friendly",
                            NameTr = "Aile Dostu"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Business Lunch",
                            NameTr = "İş Yemeği"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Vegan / Vegetarian",
                            NameTr = "Vegan / Vejetaryen"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Waterfront",
                            NameTr = "Deniz Kenarı"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Coffee & Dessert",
                            NameTr = "Kahve & Tatlı"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Nightlife",
                            NameTr = "Gece Hayatı"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Brunch",
                            NameTr = "Brunch"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Fast Food",
                            NameTr = "Fast Food"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Fine Dining",
                            NameTr = "Fine Dining"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Historic Venue",
                            NameTr = "Tarihî Mekân"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Pet Friendly",
                            NameTr = "Köpek Dostu"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Tea Garden",
                            NameTr = "Çay Bahçesi"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Sports Event",
                            NameTr = "Spor Etkinliği"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Art & Culture",
                            NameTr = "Sanat & Kültür"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Bosphorus View",
                            NameTr = "Boğaz Manzarası"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Hookah",
                            NameTr = "Nargile"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Playground",
                            NameTr = "Oyun Alanı"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Rooftop",
                            NameTr = "Rooftop"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsSystem = true,
                            NameEn = "Work Friendly",
                            NameTr = "Çalışma Dostu"
                        });
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("İstanbul");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("districts", "venue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            Name = "Adalar"
                        },
                        new
                        {
                            Id = 2,
                            City = "İstanbul",
                            Name = "Arnavutköy"
                        },
                        new
                        {
                            Id = 3,
                            City = "İstanbul",
                            Name = "Ataşehir"
                        },
                        new
                        {
                            Id = 4,
                            City = "İstanbul",
                            Name = "Avcılar"
                        },
                        new
                        {
                            Id = 5,
                            City = "İstanbul",
                            Name = "Bağcılar"
                        },
                        new
                        {
                            Id = 6,
                            City = "İstanbul",
                            Name = "Bahçelievler"
                        },
                        new
                        {
                            Id = 7,
                            City = "İstanbul",
                            Name = "Bakırköy"
                        },
                        new
                        {
                            Id = 8,
                            City = "İstanbul",
                            Name = "Başakşehir"
                        },
                        new
                        {
                            Id = 9,
                            City = "İstanbul",
                            Name = "Bayrampaşa"
                        },
                        new
                        {
                            Id = 10,
                            City = "İstanbul",
                            Name = "Beşiktaş"
                        },
                        new
                        {
                            Id = 11,
                            City = "İstanbul",
                            Name = "Beykoz"
                        },
                        new
                        {
                            Id = 12,
                            City = "İstanbul",
                            Name = "Beylikdüzü"
                        },
                        new
                        {
                            Id = 13,
                            City = "İstanbul",
                            Name = "Beyoğlu"
                        },
                        new
                        {
                            Id = 14,
                            City = "İstanbul",
                            Name = "Büyükçekmece"
                        },
                        new
                        {
                            Id = 15,
                            City = "İstanbul",
                            Name = "Çatalca"
                        },
                        new
                        {
                            Id = 16,
                            City = "İstanbul",
                            Name = "Çekmeköy"
                        },
                        new
                        {
                            Id = 17,
                            City = "İstanbul",
                            Name = "Esenler"
                        },
                        new
                        {
                            Id = 18,
                            City = "İstanbul",
                            Name = "Esenyurt"
                        },
                        new
                        {
                            Id = 19,
                            City = "İstanbul",
                            Name = "Eyüpsultan"
                        },
                        new
                        {
                            Id = 20,
                            City = "İstanbul",
                            Name = "Fatih"
                        },
                        new
                        {
                            Id = 21,
                            City = "İstanbul",
                            Name = "Gaziosmanpaşa"
                        },
                        new
                        {
                            Id = 22,
                            City = "İstanbul",
                            Name = "Güngören"
                        },
                        new
                        {
                            Id = 23,
                            City = "İstanbul",
                            Name = "Kadıköy"
                        },
                        new
                        {
                            Id = 24,
                            City = "İstanbul",
                            Name = "Kağıthane"
                        },
                        new
                        {
                            Id = 25,
                            City = "İstanbul",
                            Name = "Kartal"
                        },
                        new
                        {
                            Id = 26,
                            City = "İstanbul",
                            Name = "Küçükçekmece"
                        },
                        new
                        {
                            Id = 27,
                            City = "İstanbul",
                            Name = "Maltepe"
                        },
                        new
                        {
                            Id = 28,
                            City = "İstanbul",
                            Name = "Pendik"
                        },
                        new
                        {
                            Id = 29,
                            City = "İstanbul",
                            Name = "Sancaktepe"
                        },
                        new
                        {
                            Id = 30,
                            City = "İstanbul",
                            Name = "Sarıyer"
                        },
                        new
                        {
                            Id = 31,
                            City = "İstanbul",
                            Name = "Silivri"
                        },
                        new
                        {
                            Id = 32,
                            City = "İstanbul",
                            Name = "Sultanbeyli"
                        },
                        new
                        {
                            Id = 33,
                            City = "İstanbul",
                            Name = "Sultangazi"
                        },
                        new
                        {
                            Id = 34,
                            City = "İstanbul",
                            Name = "Şile"
                        },
                        new
                        {
                            Id = 35,
                            City = "İstanbul",
                            Name = "Şişli"
                        },
                        new
                        {
                            Id = 36,
                            City = "İstanbul",
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = 37,
                            City = "İstanbul",
                            Name = "Ümraniye"
                        },
                        new
                        {
                            Id = 38,
                            City = "İstanbul",
                            Name = "Üsküdar"
                        },
                        new
                        {
                            Id = 39,
                            City = "İstanbul",
                            Name = "Zeytinburnu"
                        });
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParkingStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("venues", "venue");
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.VenueConcept", b =>
                {
                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConceptTagId")
                        .HasColumnType("integer");

                    b.HasKey("VenueId", "ConceptTagId");

                    b.HasIndex("ConceptTagId");

                    b.ToTable("venue_concepts", "venue");
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.VenuePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsMenuPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("venue_photos", "venue");
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.Venue", b =>
                {
                    b.HasOne("SpotFinder.VenueService.Data.Entities.District", "District")
                        .WithMany("Venues")
                        .HasForeignKey("DistrictId");

                    b.Navigation("District");
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.VenueConcept", b =>
                {
                    b.HasOne("SpotFinder.VenueService.Data.Entities.ConceptTag", "ConceptTag")
                        .WithMany("VenueConcepts")
                        .HasForeignKey("ConceptTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotFinder.VenueService.Data.Entities.Venue", "Venue")
                        .WithMany("VenueConcepts")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConceptTag");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.VenuePhoto", b =>
                {
                    b.HasOne("SpotFinder.VenueService.Data.Entities.Venue", "Venue")
                        .WithMany("Photos")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.ConceptTag", b =>
                {
                    b.Navigation("VenueConcepts");
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.District", b =>
                {
                    b.Navigation("Venues");
                });

            modelBuilder.Entity("SpotFinder.VenueService.Data.Entities.Venue", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("VenueConcepts");
                });
#pragma warning restore 612, 618
        }
    }
}
